server:
  port: 8090

spring:
  application:
    name: Integration-Test-Service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

services:
  user-service:
    name: USER-SERVICE
  habit-service:
    name: HABIT-SERVICE
  reward-service:
    name: REWARD-SERVICE